FintasticFish.Web/Controllers/FishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FintasticFish.Data;
using FintasticFish.Data.Entities;
using SixLabors.ImageSharp.Formats.Webp;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;

namespace FintasticFish.Web.Controllers
{
    public class FishController : Controller
    {
        private readonly FintasticFishContext _context;

        public FishController(FintasticFishContext context)
        {
            _context = context;
        }

        // GET: Fish
        public async Task<IActionResult> Index()
        {
            var fintasticFishContext = _context.Fishes
                                      .Include(f => f.AggressionLevel)
                                      .Include(f => f.AggressionType)
                                      .Include(f => f.Country)
                                      .Include(f => f.Measurement)
                                      .Include(f => f.Supplier)
                                      .Include(f => f.WaterType);
            return View(await fintasticFishContext.ToListAsync());
        }

        // GET: Fish/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fishes
                .Include(f => f.AggressionLevel)
                .Include(f => f.AggressionType)
                .Include(f => f.Country)
                .Include(f => f.Measurement)
                .Include(f => f.Supplier)
                .Include(f => f.WaterType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fish == null)
            {
                return NotFound();
            }

            return View(fish);
        }

        // GET: Fish/Create
        public IActionResult Create()
        {
            ViewData["AggressionTypeId"] = new SelectList(_context.AggressionTypes, "Id", "Name");
            ViewData["AggressionLevelId"] = new SelectList(_context.AggressionLevels, "Id", "Name");
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name");
            ViewData["MeasurementId"] = new SelectList(_context.Measurements, "Id", "Name");
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name");
            ViewData["WaterTypeId"] = new SelectList(_context.WaterTypes, "Id", "Name");
            return View();
        }

        // POST: Fish/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Species,Size,MeasurementId,Color,Price,Stock,IsSpecialOrder,Description,FormFile,CountryId,SupplierId,WaterTypeId,AggressionLevelId,AggressionTypeId")] Fish fish)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    fish.Image = await BuildWebpFromFormFile(fish.FormFile);
                    _context.Add(fish);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    //todo: log this error
                }
            }

            ViewData["AggressionTypeId"] = new SelectList(_context.AggressionTypes, "Id", "Name", fish.AggressionTypeId);
            ViewData["AggressionLevelId"] = new SelectList(_context.AggressionLevels, "Id", "Name", fish.AggressionLevelId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", fish.CountryId);
            ViewData["MeasurementId"] = new SelectList(_context.Measurements, "Id", "Name", fish.MeasurementId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", fish.SupplierId);
            ViewData["WaterTypeId"] = new SelectList(_context.WaterTypes, "Id", "Name", fish.WaterTypeId);
            return View(fish);
        }

        public async Task<FileResult> GetFishImage(int id)
        {
            Fish? fish = await _context.Fishes.FindAsync(id);
            
            return File(fish!.Image, "image/jpg");
        }

        //https://docs.sixlabors.com/articles/imagesharp/gettingstarted.html
        private async Task<byte[]> BuildWebpFromFormFile(IFormFile formFile)
        {
            using var memoryStream = new MemoryStream();
            await formFile.CopyToAsync(memoryStream);
            // When you are copying to a stream you are leaving the stream position at the end of the stream
            // not at the beginning. You need to set the position to 0
            memoryStream.Position = 0;
            using var myImage = await Image.LoadAsync(memoryStream);
            var newSize = new Size(275, 183); // Example size, adjust as needed
            var paddingColor = Color.Black; // Example padding color, adjust as needed
            myImage.Mutate(x => x.Resize(new ResizeOptions
            {
                Mode = ResizeMode.BoxPad,
                Size = newSize,
                Position = AnchorPositionMode.Center, // Position of the image within the padding
                PadColor = paddingColor
            }));
            using var outStream = new MemoryStream();
            await myImage.SaveAsync(outStream, new WebpEncoder());
            return outStream.ToArray();
        }

        // GET: Fish/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fishes.FindAsync(id);
            if (fish == null)
            {
                return NotFound();
            }
            ViewData["AggressionLevelId"] = new SelectList(_context.AggressionLevels, "Id", "Name", fish.AggressionLevelId);
            ViewData["AggressionTypeId"] = new SelectList(_context.AggressionTypes, "Id", "Name", fish.AggressionTypeId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", fish.CountryId);
            ViewData["MeasurementId"] = new SelectList(_context.Measurements, "Id", "Name", fish.MeasurementId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", fish.SupplierId);
            ViewData["WaterTypeId"] = new SelectList(_context.WaterTypes, "Id", "Name", fish.WaterTypeId);
            return View(fish);
        }

        // POST: Fish/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Species,Size,MeasurementId,Color,Price,Stock,IsSpecialOrder,Description,FormFile,CountryId,SupplierId,WaterTypeId,AggressionLevelId,AggressionTypeId")] Fish fish)
        {
            if (id != fish.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    fish.Image = await BuildWebpFromFormFile(fish.FormFile);
                    _context.Update(fish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishExists(fish.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AggressionLevelId"] = new SelectList(_context.AggressionLevels, "Id", "Name", fish.AggressionLevelId);
            ViewData["AggressionTypeId"] = new SelectList(_context.AggressionTypes, "Id", "Name", fish.AggressionTypeId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", fish.CountryId);
            ViewData["MeasurementId"] = new SelectList(_context.Measurements, "Id", "Name", fish.MeasurementId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", fish.SupplierId);
            ViewData["WaterTypeId"] = new SelectList(_context.WaterTypes, "Id", "Name", fish.WaterTypeId);
            return View(fish);
        }

        // GET: Fish/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fishes
                .Include(f => f.AggressionLevel)
                .Include(f => f.AggressionType)
                .Include(f => f.Country)
                .Include(f => f.Measurement)
                .Include(f => f.Supplier)
                .Include(f => f.WaterType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fish == null)
            {
                return NotFound();
            }

            return View(fish);
        }

        // POST: Fish/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fish = await _context.Fishes.FindAsync(id);
            if (fish != null)
            {
                _context.Fishes.Remove(fish);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FishExists(int id)
        {

FintasticFish.Web/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FintasticFish.Data.Entities;

namespace FintasticFish.Web.Controllers
{
    public class FoodsController : Controller
    {
        private readonly FintasticFishContext _context;

        public FoodsController(FintasticFishContext context)
        {
            _context = context;
        }

        // GET: Foods
        public async Task<IActionResult> Index()
        {
            var fintasticFishContext = _context.Foods.Include(f => f.FoodType)
                                                     .Include(f => f.Mearsurement)
                                                     .Include(f => f.Supplier);
            return View(await fintasticFishContext.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .Include(f => f.FoodType)
                .Include(f => f.Mearsurement)
                .Include(f => f.Supplier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        public IActionResult Create()
        {
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "Name");
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name");
            ViewData["MearsurementId"] = new SelectList(_context.Measurements, "Id", "Name");
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,SalePrice,Size,Taxable,Description,Stock,SupplierId,SaleStartDate,SaleEndDate,FoodTypeId,MearsurementId")] Food food)
        {
            if (ModelState.IsValid)
            {
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "Name", food.FoodTypeId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", food.SupplierId);
            ViewData["MearsurementId"] = new SelectList(_context.Measurements, "Id", "Name", food.MearsurementId);
            return View(food);
        }

        // GET: Foods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "Name", food.FoodTypeId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", food.SupplierId);
            ViewData["MearsurementId"] = new SelectList(_context.Measurements, "Id", "Name", food.MearsurementId);
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,SalePrice,Size,Taxable,Description,Stock,SupplierId,SaleStartDate,SaleEndDate,FoodTypeId,MearsurementId")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "Name", food.FoodTypeId);
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", food.SupplierId);
            ViewData["MearsurementId"] = new SelectList(_context.Measurements, "Id", "Name", food.MearsurementId);
            return View(food);
        }

        // GET: Foods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .Include(f => f.FoodType)
                .Include(f => f.Mearsurement)
                .Include(f => f.Supplier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Foods.FindAsync(id);
            if (food != null)
            {
                _context.Foods.Remove(food);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Foods.Any(e => e.Id == id);
        }
    }
}

FintasticFish.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fin-Tastic Fish</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SampleApplication.styles.css" asp-append-version="true" />
    <link rel="icon" href="/Images/AI_Fintastic1.webp" type="image/x-icon">


</head>
<body data-bs-theme="light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-1 fixed-top">

           <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SampleApplication</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fish" asp-action="Index">Fish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Foods" asp-action="Index">Foods</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Plants" asp-action="Index">Plants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AquaSupplies" asp-action="Index">Supplies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Suppliers" asp-action="Index">My Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div>
            <address>
                <div class="flex-container-footer">
                    <div class="flex-item">
                        Fin-Tastic Fish<br>
                        724 Fort Crook Rd N Bellevue, NE 68005<br>
                        Contact us at 402-305-8815<br />
                        &copy; 2024 - FintasticFish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                    <div class="flex-item">
                        <a class="social-link social-link:hover" href="https://www.facebook.com/FintasticFishBellevue/"></a>
                    </div>
                    <div class="flex-item">
                        Hours of Operation: <br>
                        Sunday: 12-6pm<br>
                        Monday: Closed<br>
                        Tuesday-Saturday 12-8pm
                    </div>
                </div>
            </address>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>